apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: ronfflex/fleet-management
            args:
            - /bin/sh
            - -c
            - /backup-script.sh
          restartPolicy: OnFailure
