- name: Configure web dev environment # This is the name of your Ansible Playbook.
  hosts: web-servers # Your target hosts where you want to setup the web development environment.
  become: yes # Elevate the privilege level to root, as most package installations require root access.
  tasks:
    - name: Update package list # Before installing packages, it's good practice to update the apt package list.
      apt:
        update_cache: yes

    - name: Install packages # Install the required packages, in this case 'fish' and 'tmux'.
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - fish
          - tmux

    - name: Clone dotfiles # Clone the Git repository which contains the necessary configuration files.
      git:
        repo: "https://github.com/MTthoas/Fleet-Management.git"
        dest: "~/dotfiles"
        clone: yes
        update: yes
      become: no # Git operations are typically performed as a regular user, not root.

    - name: Ensure fish config directory exists # Create the directory for the 'fish' configuration file, if it doesn't exist.
      file:
        path: "~/.config/fish"
        state: directory
      become: no # File operations are typically performed as a regular user, not root.

    - name: Link fish config # Create a symbolic link to the 'fish' configuration file.
      file:
        src: "~/dotfiles/fish/config.fish"
        dest: "~/.config/fish/config.fish"
        state: link
      become: no

    - name: Link tmux config # Create a symbolic link to the 'tmux' configuration file.
      file:
        src: "~/dotfiles/tmux/.tmux.conf"
        dest: "~/.tmux.conf"
        state: link
      become: no
